const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Update client records",
        description: "Ensure all client records are up to date",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "administration",
      },
      {
        title: "Weekly report",
        description: "Submit weekly progress report",
        date: "2025-11-30",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        weightage: "med",
        category: "reporting",
      },
      {
        title: "Team meeting prep",
        description: "Prepare agenda for team meeting",
        date: "2025-11-28",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        weightage: "low",
        category: "meeting",
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Database backup",
        description: "Take backup of production DB",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "database",
      },
      {
        title: "Code review",
        description: "Review PR #23 and provide feedback",
        date: "2025-11-28",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        weightage: "med",
        category: "development",
      },
      {
        title: "Update documentation",
        description: "Update API docs with latest changes",
        date: "2025-11-30",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "low",
        category: "documentation",
      },
      {
        title: "Fix login bug",
        description: "Resolve issue causing login failures",
        date: "2025-11-27",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        weightage: "high",
        category: "bugfix",
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Client call",
        description: "Call client to discuss requirements",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "client",
      },
      {
        title: "Design mockups",
        description: "Prepare UI mockups for dashboard",
        date: "2025-11-30",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        weightage: "med",
        category: "design",
      },
      {
        title: "Server maintenance",
        description: "Check server logs and update patches",
        date: "2025-11-28",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        weightage: "low",
        category: "infrastructure",
      },
      {
        title: "Team lunch",
        description: "Organize team lunch on Friday",
        date: "2025-11-27",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        weightage: "low",
        category: "social",
      },
      {
        title: "Performance review",
        description: "Prepare performance review documents",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "hr",
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Bug triage",
        description: "Prioritize and assign bugs",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "development",
      },
      {
        title: "Write unit tests",
        description: "Add unit tests for user module",
        date: "2025-11-30",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        weightage: "med",
        category: "testing",
      },
      {
        title: "Update roadmap",
        description: "Update project roadmap for next sprint",
        date: "2025-11-28",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        weightage: "low",
        category: "planning",
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Prepare presentation",
        description: "Prepare slides for client demo",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "presentation",
      },
      {
        title: "Deploy app",
        description: "Deploy latest version to staging",
        date: "2025-11-30",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        weightage: "med",
        category: "deployment",
      },
      {
        title: "Code cleanup",
        description: "Remove unused code and comments",
        date: "2025-11-28",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        weightage: "low",
        category: "maintenance",
      },
      {
        title: "Client feedback",
        description: "Collect and document feedback from client",
        date: "2025-11-27",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        weightage: "med",
        category: "client",
      },
      {
        title: "Team workshop",
        description: "Conduct internal workshop on new tools",
        date: "2025-11-29",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        weightage: "high",
        category: "training",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
 const employees= JSON.parse(localStorage.getItem('employees'))
 const admin= JSON.parse(localStorage.getItem('admin'))
 
 console.log(employees,admin);
  

 

};
